// Define the data array
export const data = [
  {
    name: "Adarsh",
    email: "adarsh@example.com",
    role: "L1",
    status: "Active",
    shift: "Morning",
  },
  {
    name: "Anurag",
    email: "anurag@example.com",
    role: "L1",
    status: "Active",
    shift: "Morning",
  },
  {
    name: "Arsalan",
    email: "arsalan@example.com",
    role: "L1",
    status: "Inactive",
    shift: "Evening",
  },
  {
    name: "Bhavesh",
    email: "bhavesh@example.com",
    role: "L1",
    status: "Active",
    shift: "Morning",
  },
  {
    name: "Unnati",
    email: "unnati@example.com",
    role: "L1",
    status: "Inactive",
    shift: "Evening",
  },
  {
    name: "Kishoree",
    email: "kishoree@example.com",
    role: "L1",
    status: "Active",
    shift: "Morning",
  },
  {
    name: "Shivani",
    email: "shivani@example.com",
    role: "L2",
    status: "Inactive",
    shift: "Evening",
  },
  {
    name: "Sumit",
    email: "sumit@example.com",
    role: "L2",
    status: "Active",
    shift: "Morning",
  },
  {
    name: "Tuaha",
    email: "tuaha@example.com",
    role: "L2",
    status: "Inactive",
    shift: "Evening",
  },
  {
    name: "Nikita",
    email: "nikita@example.com",
    role: "L1",
    status: "Active",
    shift: "Morning",
  },
  {
    name: "Mashnu",
    email: "mashnu@example.com",
    role: "L2",
    status: "Inactive",
    shift: "Evening",
  },
  {
    name: "Aditya",
    email: "aditya@example.com",
    role: "L1",
    status: "Active",
    shift: "Morning",
  },
  {
    name: "Archie",
    email: "archie@example.com",
    role: "L1",
    status: "Inactive",
    shift: "Evening",
  },
  {
    name: "Monik",
    email: "monik@example.com",
    role: "L1",
    status: "Active",
    shift: "Morning",
  },
  {
    name: "Neha",
    email: "neha@example.com",
    role: "L1",
    status: "Inactive",
    shift: "Evening",
  },
  {
    name: "Samarth",
    email: "samarth@example.com",
    role: "L1",
    status: "Active",
    shift: "Morning",
  },
  {
    name: "Shubhankar",
    email: "shubhankar@example.com",
    role: "L1",
    status: "Inactive",
    shift: "Evening",
  },
  {
    name: "Simran",
    email: "simran@example.com",
    role: "L1",
    status: "Active",
    shift: "Morning",
  },
  {
    name: "Shreya",
    email: "shreya@example.com",
    role: "L1",
    status: "Inactive",
    shift: "Evening",
  },
  {
    name: "Tamanna",
    email: "tamanna@example.com",
    role: "L1",
    status: "Active",
    shift: "Morning",
  },
  {
    name: "Adish",
    email: "adish@example.com",
    role: "L1",
    status: "Inactive",
    shift: "Evening",
  },
  {
    name: "Debashish",
    email: "debashish@example.com",
    role: "L1",
    status: "Active",
    shift: "Morning",
  },
  {
    name: "Shweta",
    email: "shweta@example.com",
    role: "L1",
    status: "Inactive",
    shift: "Evening",
  },
];
