// Define the data array with joining dates
export const data = [
  {
    name: "Adarsh",
    email: "adarsh@example.com",
    role: "L1",
    shift: "Morning",
    manager: "Anmol",
    joiningDate: "2023-06-15",
  },
  {
    name: "Anurag",
    email: "anurag@example.com",
    role: "L1",
    shift: "Morning",
    manager: "Imtiyaz",
    joiningDate: "2023-05-10",
  },
  {
    name: "Arsalan",
    email: "arsalan@example.com",
    role: "L1",
    shift: "Evening",
    manager: "Anmol",
    joiningDate: "2023-08-20",
  },
  {
    name: "Bhavesh",
    email: "bhavesh@example.com",
    role: "L1",
    shift: "Morning",
    manager: "Imtiyaz",
    joiningDate: "2023-07-01",
  },
  {
    name: "Unnati",
    email: "unnati@example.com",
    role: "L1",
    shift: "Evening",
    manager: "Anmol",
    joiningDate: "2023-04-12",
  },
  {
    name: "Kishoree",
    email: "kishoree@example.com",
    role: "L2",
    shift: "Morning",
    manager: "Imtiyaz",
    joiningDate: "2023-03-25",
  },
  {
    name: "Shivani",
    email: "shivani@example.com",
    role: "L2",
    shift: "Evening",
    manager: "Anmol",
    joiningDate: "2023-02-18",
  },
  {
    name: "Sumit",
    email: "sumit@example.com",
    role: "L2",
    shift: "Morning",
    manager: "Imtiyaz",
    joiningDate: "2023-07-15",
  },
  {
    name: "Tuaha",
    email: "tuaha@example.com",
    role: "L2",
    shift: "Evening",
    manager: "Anmol",
    joiningDate: "2023-01-20",
  },
  {
    name: "Nikita",
    email: "nikita@example.com",
    role: "L1",
    shift: "Morning",
    manager: "Imtiyaz",
    joiningDate: "2023-06-28",
  },
  {
    name: "Mashnu",
    email: "mashnu@example.com",
    role: "L2",
    shift: "Evening",
    manager: "Anmol",
    joiningDate: "2023-05-05",
  },
  {
    name: "Aditya",
    email: "aditya@example.com",
    role: "L1",
    shift: "Morning",
    manager: "Imtiyaz",
    joiningDate: "2023-08-02",
  },
  {
    name: "Archie",
    email: "archie@example.com",
    role: "L1",
    shift: "Evening",
    manager: "Anmol",
    joiningDate: "2023-07-22",
  },
  {
    name: "Monik",
    email: "monik@example.com",
    role: "L1",
    shift: "Morning",
    manager: "Imtiyaz",
    joiningDate: "2023-05-18",
  },
  {
    name: "Neha",
    email: "neha@example.com",
    role: "L1",
    shift: "Evening",
    manager: "Anmol",
    joiningDate: "2023-03-30",
  },
  {
    name: "Samarth",
    email: "samarth@example.com",
    role: "L1",
    shift: "Morning",
    manager: "Imtiyaz",
    joiningDate: "2023-04-08",
  },
  {
    name: "Shubhankar",
    email: "shubhankar@example.com",
    role: "L1",
    shift: "Evening",
    manager: "Anmol",
    joiningDate: "2023-02-14",
  },
  {
    name: "Simran",
    email: "simran@example.com",
    role: "L1",
    shift: "Night",
    manager: "Imtiyaz",
    joiningDate: "2023-01-10",
  },
  {
    name: "Shreya",
    email: "shreya@example.com",
    role: "L1",
    shift: "Evening",
    manager: "Anmol",
    joiningDate: "2023-08-16",
  },
  {
    name: "Tamanna",
    email: "tamanna@example.com",
    role: "L1",
    shift: "Morning",
    manager: "Imtiyaz",
    joiningDate: "2023-09-01",
  },
  {
    name: "Adish",
    email: "adish@example.com",
    role: "L1",
    shift: "Night",
    manager: "Anmol",
    joiningDate: "2023-02-05",
  },
  {
    name: "Debashish",
    email: "debashish@example.com",
    role: "L1",
    shift: "Morning",
    manager: "Imtiyaz",
    joiningDate: "2023-06-10",
  },
  {
    name: "Shweta",
    email: "shweta@example.com",
    role: "L1",
    shift: "Evening",
    manager: "Anmol",
    joiningDate: "2023-04-24",
  },
];
